---
- name: "PLAY 1: SETUP CLUSTER"
  connection: local
  hosts: localhost
  vars:
    vms:
      - { name: gns3, address: 192.168.0.101/24 }
      - { name: awx, address: 192.168.0.102/24 }
      - { name: prometheus, address: 192.168.0.104/24 }
      - { name: docker01, address: 192.168.0.105/24 }
      - { name: docker02, address: 192.168.0.106/24 }
    pves:
      - { name: pve01, address: "192.168.0.254/24" }
      - { name: pve02, address: "192.168.0.253/24" }
    nautobot_headers:
      Content-Type: "application/json"
      Authorization: "token {{ lookup('ENV', 'NAUTOBOT_TOKEN') }}"
    url: "{{ lookup('ENV', 'NAUTOBOT_URL') }}"
    token: "{{ lookup('ENV', 'NAUTOBOT_TOKEN') }}"
  tasks:
    - name: "TASK 0: CREATE CLUSTER TYPE"
      networktocode.nautobot.cluster_type:
        url: "{{ lookup('ENV', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('ENV', 'NAUTOBOT_TOKEN') }}"
        data:
          name: Proxmox
        state: present

    - name: "TASK 1: SYS >> ADD VM CLUSTER"
      networktocode.nautobot.cluster:
        url: "{{ lookup('ENV', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('ENV', 'NAUTOBOT_TOKEN') }}"
        data:
          name: JoshV_Cluster1
          cluster_type: Proxmox
        state: present

    - name: "TASK 2: SYS >> CREATE CLUSTER HOSTS"
      networktocode.nautobot.device:
        url: "{{ lookup('ENV', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('ENV', 'NAUTOBOT_TOKEN') }}"
        data:
          name: "{{ item.name }}"
          device_type: CustomServer
          device_role: Server
          site: minnesota01
      loop: "{{ pves }}"

    - name: "TASK 3: SYS >> SETUP SOME VMs"
      networktocode.nautobot.virtual_machine:
        url: "{{ lookup('ENV', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('ENV', 'NAUTOBOT_TOKEN') }}"
        data:
          name: "{{ item.name }}"
          cluster: JoshV_Cluster1
        state: present
      loop: "{{ vms }}"

    - name: "TASK 4: SYS >> Create interfaces"
      networktocode.nautobot.vm_interface:
        url: "{{ lookup('ENV', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('ENV', 'NAUTOBOT_TOKEN') }}"
        data:
          virtual_machine: "{{ item.name }}"
          name: eth0
        state: present
      loop: "{{ vms }}"

    - name: "TASK 5: SYS >> ASSIGN IP TO VM"
      uri:
        url: "{{ lookup('ENV', 'NAUTOBOT_URL') }}/api/ipam/ip-addresses/"
        method: POST
        headers: "{{ nautobot_headers }}"
        status_code: 201
        body_format: json
        body: {
          "address": "{{ item.address }}",
          "status": 1,
          "interface": "{{ item.name | get_interface_id(nautobot_headers) }}"
        }
      loop: "{{ vms }}"

    - name: "TASK 6: SYS >> ASSIGN PRIMARY ADDRESS TO THE DEVICE"
      networktocode.nautobot.virtual_machine:
        url: "{{ lookup('ENV', 'NAUTOBOT_URL') }}"
        token: "{{ lookup('ENV', 'NAUTOBOT_TOKEN') }}"
        data:
          name: "{{ item.name }}"
          cluster: JoshV_Cluster1
          primary_ip4: "{{ item.address }}"
        state: present
      loop: "{{ vms }}"
